name: ReleaseWorkflow

on:
  release:
    types: [published]


jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Create new Sentry release and deploy
        run: | 
          curl -sL https://sentry.io/get-cli/ | bash

          export VERSION=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $VERSION
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE

          sentry-cli releases deploys $SENTRY_RELEASE new -e production
