name: ReleaseWorkflow

on:
  release:
    types: [published]


jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{secrets.SENTRY_ORG}}
      SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: yarn install
      - name: Build the applicaiton
        run: yarn build
      - name: Create Sentry release
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          VERSION=$(sentry-cli releases propose-version)
          sentry-cli releases new -p bored $VERSION
          sentry-cli releases set-commits --auto $VERSION
          sentry-cli releases finalize $VERSION
          sentry-cli releases files $VERSION upload-sourcemaps build/static/js --url-prefix '~/static/js' --no-rewrite
          sentry-cli releases deploys $VERSION new -e "production"